In [1]:
from IPython.display import Image

# NumPy?

Numerical Python<br>

Python에서 **대규모 다차원 배열**을 다룰 수 있게 도와주는 라이브러리<br>

## Python list?

파이썬 리스트에 비해, 빠른 연산을 지원하고 메모리르 효율적으로 사용<br>

![nn](function.png)

In [2]:
# 0부터 5사이 랜덤한 값이 담긴 3x5 array를 만들어 보자.

import numpy as np

array = np.random.randint(0,5,(3,5))
print(array)

[[3 0 2 3 0]
 [0 2 3 0 0]
 [3 1 4 1 4]]


# Python List와 다르게 array 는 단일 타입으로 구성
```python
arr = np.array([1,2,3,4], dtype=float)
arr  # array([1., 2., 3., 4.])
arr.dtype  # dtype('float64')
arr.astype(int) # array(1, 2, 3, 4])
```

## numpy 배열 기초

In [3]:
np.zeros(10, dtype=int) # 10크기의 0 삽입

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.ones((3,5), dtype=float) # 3x5 크기의 float 형 1 삽입

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [6]:
np.arange(0,20,2) # 간격이 2씩 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
np.linspace(0,1,5) # 소수점 분해 5개로

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [13]:
import numpy as np

print("1차원 array")
array = np.arange(10)
print(array)

# Q1. array의 자료형을 출력해보세요.
print(type(array))

# Q2. array의 차원을 출력해보세요.
print(array.ndim)

# Q3. array의 모양을 출력해보세요.
print(array.shape)

# Q4. array의 크기를 출력해보세요.
print(array.size)

# Q5. array의 dtype(data type)을 출력해보세요.
print(array.dtype)

# Q6. array의 인덱스 5의 요소를 출력해보세요.
print(array[5])

# Q7. array의 인덱스 3의 요소부터 인덱스 5 요소까지 출력해보세요.
print(array[3:6])


1차원 array
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
1
(10,)
10
int64
5
[3 4 5]


In [14]:
import numpy as np

print("2차원 array")
matrix = np.arange(1, 16).reshape(3,5)  #1부터 15까지 들어있는 (3,5)짜리 배열을 만듭니다.
print(matrix)


# Q1. matrix의 자료형을 출력해보세요.

print(type(matrix))
# Q2. matrix의 차원을 출력해보세요.
print(matrix.ndim)

# Q3. matrix의 모양을 출력해보세요.
print(matrix.shape)

# Q4. matrix의 크기를 출력해보세요.
print(matrix.size)

# Q5. matrix의 dtype(data type)을 출력해보세요.

print(matrix.dtype)
# Q6. matrix의 (2,3) 인덱스의 요소를 출력해보세요.
print(matrix[2,3])

# Q7. matrix의 행은 인덱스 0부터 인덱스 1까지, 열은 인덱스 1부터 인덱스 3까지 출력해보세요.
print(matrix[0:2,1:4])



2차원 array
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int64
14
[[2 3 4]
 [7 8 9]]
