# 브로드캐스팅

Broadcasting : shape이 다른 array끼리 연산

In [1]:
import numpy as np

A=np.arange(6).reshape(6,1)
B=np.arange(6).reshape(1,6)
print(A+B)



[[ 0  1  2  3  4  5]
 [ 1  2  3  4  5  6]
 [ 2  3  4  5  6  7]
 [ 3  4  5  6  7  8]
 [ 4  5  6  7  8  9]
 [ 5  6  7  8  9 10]]


# 집계 함수

집계 : 데이터에 대한 요약 통계
<br>

In [2]:
import numpy as np

matrix = np.arange(8).reshape((2, 4))
print(matrix)

# Q1. sum 함수로 matrix의 총 합계를 구해 출력해보세요.

print(np.sum(matrix))
# Q2. max 함수로 matrix 중 최댓값을 구해 출력해보세요.
print(np.max(matrix))

# Q3. min 함수로 matrix 중 최솟값을 구해 출력해보세요.

print(np.min(matrix))
# Q4. mean 함수로 matrix의 평균값을 구해 출력해보세요.
print(np.mean(matrix))

# Q5. sum 함수의 axis 매개변수로 각 열의 합을 구해 출력해보세요.
print(np.sum(matrix, axis=0))

# Q6. sum 함수의 axis 매개변수로 각 행의 합을 구해 출력해보세요.
print(np.sum(matrix, axis=1))


# Q7. std 함수로 matrix의 표준편차를 구해 출력해보세요.
print(np.std(matrix))

# Q8. 마스킹 연산을 이용하여 matrix 중 5보다 작은 수들만 추출하여 출력해보세요.
print(matrix[matrix<5])

[[0 1 2 3]
 [4 5 6 7]]
28
7
0
3.5
[ 4  6  8 10]
[ 6 22]
2.29128784747792
[0 1 2 3 4]



# 마스킹 연산

마스킹 연산 : True, False array를 통해서 특정 값들을 뽑아내는 방법

In [3]:
x = np.arange(5)
print(x)

print(x<3)

print(x>5)

print(x[x<3])

[0 1 2 3 4]
[ True  True  True False False]
[False False False False False]
[0 1 2]


In [4]:

import numpy as np

daily_liar_data = [0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0]


# 양치기 소년이 거짓말을 몇 번 했는지 구하여 출력해주세요.

def main():
    liar_array = np.array(daily_liar_data)
    
    print(len(liar_array[liar_array == 0]))

if __name__ == "__main__":
    main()

71
