# 모양 바꾸기

np.concatenate: axis 축 기준으로 1이면 가로 0이면 세로

In [2]:
import numpy as np

print("matrix")
matrix = np.array([[0,1,2,3],
                   [4,5,6,7]])
print(matrix)
print("shape : ", matrix.shape, "\n")

# (아래의 배열 모양을 참고하세요.)
# Q1. matrix 두 개를 세로로 붙이기 
m = np.concatenate([matrix, matrix], axis=0)
print(m)
# Q2. matrix 두 개를 가로로 붙이기 
n = np.concatenate([matrix, matrix], axis=1)
print(n)

matrix
[[0 1 2 3]
 [4 5 6 7]]
shape :  (2, 4) 

[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3 0 1 2 3]
 [4 5 6 7 4 5 6 7]]


np.split : axis 축을 기준으로 분할

In [4]:
import numpy as np

print("matrix")
matrix = np.array([[ 0, 1, 2, 3],
                   [ 4, 5, 6, 7],
                   [ 8, 9,10,11], 
                   [12,13,14,15]])
print(matrix, "\n")

# Q1. matrix를 [3] 행에서 axis 0으로 나누기
a, b = np.split(matrix, [3], axis=0)
print(a, "\n")
print(b, "\n")
# Q2. matrix를 [1] 열에서 axis 1로 나누기
c, d = np.split(matrix, [1], axis=1)
print(c, "\n")
print(d)


matrix
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[12 13 14 15]] 

[[ 0]
 [ 4]
 [ 8]
 [12]] 

[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


# 루프는 느리다

array의 크기가 크다면 함수적용시 느림.

In [5]:
import numpy as np

array = np.array([1,2,3,4,5])
print(array)

# Q1. array에 5를 더한 값을 출력해보세요.
print(array+5)
# Q2. array에 5를 뺀 값을 출력해보세요.
print(array-5)

# Q3. array에 5를 곱한 값을 출력해보세요.
print(array*5)

# Q4. array를 5로 나눈 값을 출력해보세요.
print(array/5)

# Q5. array에 array2를 더한 값을 출력해보세요.    
array2 = np.array([5,4,3,2,1])
print(array+array2)

# Q6. array에 array2를 뺀 값을 출력해보세요.
print(array-array2)



[1 2 3 4 5]
[ 6  7  8  9 10]
[-4 -3 -2 -1  0]
[ 5 10 15 20 25]
[0.2 0.4 0.6 0.8 1. ]
[6 6 6 6 6]
[-4 -2  0  2  4]
